# Generated by Django 2.2.7 on 2020-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='paginated',
            field=models.PositiveIntegerField(default=5, verbose_name='Количество новостей на странице'),
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(default='blog/post_list.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
