# Generated by Django 2.2.7 on 2020-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200625_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='created_date',
        ),
    ]
