# Generated by Django 2.2.7 on 2020-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
                ('template', models.CharField(default='page/index.html', max_length=1000, verbose_name='Template')),
                ('slug', models.SlugField(max_length=1000, verbose_name='url')),
            ],
        ),
    ]
