# Generated by Django 2.2.7 on 2020-06-29 14:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_auth', models.BooleanField(default=True, verbose_name='Для зарегистрированных?')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название на литинице')),
                ('title', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('status', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
                ('is_auth', models.BooleanField(default=True, verbose_name='Для зарегистрированных?')),
                ('anchor', models.CharField(max_length=30, verbose_name='Якорь')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл/Выкл')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItems', verbose_name='Родительская категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
